### ISSUE TITLE
InfoWindow DataContext

### ISSUE THREAD

**Issue by Flipmachin1001** [Gambler-LeRos/TestedTaskRepo#2]
В конструктор окна редактирования, создания заявки **InfoWindow** передается целиком модель со всеми заявками **RequestViewModel**

**Comment by Gambler-LeRos** [comment]
Потому что функционал у кнопок полностью одинаковый, весь смысл окна только в возможности оставить комментарий, так как этого поля нет в основном окне. Зачем дублировать код и плодить дополнительные связи? Передается же ссылка, а не новый экземпляр.

**Comment by aamenkov** [comment]
Проблема в том, что для редактирования **одной** заявки, передается на вход модель со **всеми** заявками внутри. 

![image](https://github.com/Gambler-LeRos/TestedTaskRepo/assets/57506749/bc344b90-e653-4ba7-afbe-1d00ae142b85)
![image](https://github.com/Gambler-LeRos/TestedTaskRepo/assets/57506749/79c30567-2385-4fb7-a0b0-bd6d749fe708)

**Comment by Gambler-LeRos** [comment]
Видимо я чего-то не понимаю, разве оба DataContext`a не будут ссылаться на один экземпляр ViewModel ?

**Comment by Ondrya** [comment]
Это кстати можно в студии проверить - посмотреть hash объекта. Если они будут разные, то это 2 разных объекта.
А в целом всегда лучше передавать минимальный набор данных в метод, не раздувая его.
Если это не объект настроек например.
Для добавления комментария к заявке в метод достаточно передать id заявки.

**Comment by Gambler-LeRos** [comment]
> Это кстати можно в студии проверить - посмотреть hash объекта. Если они будут разные, то это 2 разных объекта. 

Проверил hash объектов и он одинаковый. Следовательно передается только ссылка и это не создает дополнительной нагрузки на систему (даже если View будет содержать в себе коллекцию на миллион записей).

> А в целом всегда лучше передавать минимальный набор данных в метод, не раздувая его. Если это не объект настроек например. 

Метод никто не раздувает, я обращаюсь по ссылке к методам и данным уже инициализированного класса.
Понятное дело, что правила есть правила. Надо делать так – значит буду.

> Для добавления комментария к заявке в метод достаточно передать id заявки.

Если передать только id и работать в другой ViewModel будет ли синхронное обновление данных в MainWindow и InfoWindow, без дополнительных связей? Скомпилируйте приложение и посмотрите на его работу, тут весь смысл в визуализации.
